### PR TITLE
Add hpssacli

### PR DESCRIPTION
**Pull request by ppp0**
Raid monitoring utility for HP Smart Array G9

### CODE REVIEW

**Comment by ppp0** [comment]
@njam please review

**Comment by ppp0** [comment]
@njam not sure: I prepared the debs for Ubuntu only, as this is the preferred distro to run on Proliant G9. On puppet, though, we declare support for both wheezy and vivid...

Otoh, I could build the deb for wheezy, too, as the Smart Array in a newest incarnation is to be had on the market as an add-on card for any motherboard and an end user might be running wheezy against it

**Comment by njam** [comment]
lgtm, I would add it also for wheezy, will make things easier in puppet?

**Comment by ppp0** [comment]
@njam please review

**Comment by njam** [comment]
lgtm

**Pull request merged**
