### PR TITLE
ffmpeg does not install on wheezy

### PR DESCRIPTION
**Pull request by ppp0**
Follow-up of https://github.com/cargomedia/debian-packages/pull/82

Errors:
```sh
The following packages have unmet dependencies:
 ffmpeg : Depends: libavcodec-ffmpeg56 (>= 7:2.7) but it is not going to be installed or
                   libavcodec-ffmpeg-extra56 (>= 7:2.7) but it is not going to be installed
          Depends: libavdevice-ffmpeg56 (>= 7:2.6) but it is not going to be installed
          Depends: libavfilter-ffmpeg5 (>= 7:2.4) but it is not going to be installed
          Depends: libavformat-ffmpeg56 (>= 7:2.6) but it is not going to be installed
          Depends: libavresample-ffmpeg2 (>= 7:2.4) but it is not going to be installed
          Depends: libavutil-ffmpeg54 (>= 7:2.5) but it is not going to be installed
          Depends: libc6 (>= 2.14) but 2.13-38+deb7u8 is to be installed
          Depends: libpostproc-ffmpeg53 (>= 7:2.4) but it is not going to be installed
          Depends: libswresample-ffmpeg1 (>= 7:2.4) but it is not going to be installed
          Depends: libswscale-ffmpeg3 (>= 7:2.4) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

Checking and disabling unneeded debs (diverging from http://packages.ubuntu.com/xenial/ffmpeg)

### CODE REVIEW

**Comment by ppp0** [comment]
Finally it's compiling! @njam please review

**Comment by njam** [comment]
- upstream/signing-key.asc: Remove if not needed?

@kris-lab can you confirm the configure flags?
https://github.com/cargomedia/debian-packages/pull/89/files#diff-e425762e4bdfd93aca48a1cacc22c82fR8

rest lgtm

**Comment by ppp0** [comment]
agree, it's not needed

**Comment by ppp0** [comment]
@kris-lab please confirm the configure flags when you have time

**Comment by ppp0** [comment]
Reverting this, as @kris-lab has problems with unavailable
```
libavformat-dev : Depends: libavcodec-dev (= 7:2.8.5-1wheezy1) but it is not going to be installed
                   Depends: libavformat-ffmpeg56 (= 7:2.8.5-1wheezy1) but it is not going to be installed
                   Depends: libavutil-dev (= 7:2.8.5-1wheezy1) but it is not going to be installed
                   Depends: libswresample-dev (= 7:2.8.5-1wheezy1) but it is not going to be installed
```

**Comment by kris-lab** [comment]
@ppp0 about flags. I see we removed MP4 support (h264+aac). It's fine.

**Pull request merged**
