### PR TITLE
Upgrade janus-gateway-rtpbroadcast to v0.0.20

### PR DESCRIPTION
**Pull request by kris-lab**
Depends on https://github.com/cargomedia/janus-gateway-rtpbroadcast/releases/tag/v0.0.20

### CODE REVIEW

**Comment by kris-lab** [comment]
@njam please review

Also, what is the reason we use 
```
/vagrant/build.sh -c <codename> -p <package>
``` 
with specific codename? Can we replace this with e.g.
```
/vagrant/build.sh -c $(facter os.distro.codename) -p janus-gateway-rtpbroadcast
```
or make the `codename` optional by default set to `facter os.distro.codename`

wdyt?

cc @ppp0

**Comment by njam** [comment]
Many packages are just downloading binaries, so we can create the DEBs for all codenames from the same VM.
Agree, could be optional though.

lgtm

**Comment by kris-lab** [comment]
synced

**Comment by kris-lab** [comment]
@zazabe @fvovan plugins released, let's schedule SK release and upgrade

**Pull request merged**
