### PR TITLE
Automate README package list generation

### PR DESCRIPTION
**Pull request by dergraf**
Out of the dir tree, build README

#### **Distro**
***Package-name***

Version

Contained debs

...

### CODE REVIEW

**Comment by dergraf** [comment]
@ppp0 please review,

@njam: is it ok to use that simple python script for that? ;)

**Comment by njam** [comment]
Great :D
Could also be a separate .md file, but template works as well!

**Comment by ppp0** [comment]
As discussed, remove tailing version number and dot deb from package names

**Comment by ppp0** [comment]
may be let it call at every `reprepo` run?

**Comment by dergraf** [comment]
@ppp0, removed included versions.

**Comment by ppp0** [comment]
python is installed in `https://atlas.hashicorp.com/cargomedia/boxes/ubuntu-1504-default` by default.. I reckon the same applies to the `wheezy` box and that `python` there is in the proper version?

Otherwise LGTM

**Pull request merged**
