### PR TITLE
janus audioroom plugin

### PR DESCRIPTION
**Pull request by dergraf**

### CODE REVIEW

**Comment by ppp0** [comment]
wait for '0.0.2'

**Comment by kris-lab** [comment]
@ppp0 @dergraf new version of `audioroom` has been released https://github.com/cargomedia/janus-gateway-audioroom/releases/tag/v0.0.2

**Comment by dergraf** [comment]
@ppp0 please review 0.0.2, added wheezy package in the same commit

**Comment by ppp0** [comment]
lgtm

**Pull request merged**
