### PR TITLE
Update janus and plugins

### PR DESCRIPTION
**Pull request by ppp0**

### CODE REVIEW

**Comment by ppp0** [comment]
Waiting for https://github.com/cargomedia/janus-gateway-audioroom/pull/25 and https://github.com/cargomedia/janus-gateway-rtpbroadcast/pull/43

**Comment by ppp0** [comment]
@dergraf may be you want to take over when wait is over?

**Comment by dergraf** [comment]
@ppp0 sure, I'll take over tomorrow morning

**Comment by njam** [comment]
@kris-lab closeable?

**Pull request closed without merging**
