### PR TITLE
Upgrade janus-gateway-audioroom to v0.0.10

### PR DESCRIPTION
**Pull request by kris-lab**
https://github.com/cargomedia/janus-gateway-audioroom/releases/tag/v0.0.10

### CODE REVIEW

**Comment by kris-lab** [comment]
@njam please review

**Comment by njam** [comment]
lgtm

**Comment by kris-lab** [comment]
@fvovan @zazabe plugin has been released - let's synchronise deployment and testing.

**Comment by kris-lab** [comment]
synced

**Pull request merged**
