### PR TITLE
Improve build/sync workflow

### PR DESCRIPTION
**Pull request by dergraf**
- build packages without the requirement to sign them in the same step
- build reprepro (db|indexes|...) in the sync step on the fly

@ppp0 @njam comments?

### CODE REVIEW

**Comment by ppp0** [comment]
looks like you're beginning to love bash :+1: 

sgtm, too, agree with `else` message for `check` `checkpool`

**Comment by dergraf** [comment]
@ppp0, @njam
as I don't have the proper GPG setup I can't build the repo properly.
It would be great if you could give it a quick check, maybe outcomment the s3cmd line.

**Comment by njam** [comment]
I've sent you the passcode through another channel so you can test it.

**Comment by dergraf** [comment]
thanks! 
It's working!

**Pull request merged**
