### PR TITLE
Add ffmpeg package

### PR DESCRIPTION
**Pull request by ppp0**
Currently we build from source in the puppet module. This slows down some specs consdierably.

See [ffmpeg puppet module](https://github.com/cargomedia/puppet-packages/blob/master/modules/ffmpeg/manifests/init.pp).

cc @kris-lab @ppp0 @tomaszdurka

### CODE REVIEW

**Comment by ppp0** [comment]
Testing is invoked by [`dh_auto_test`](http://man.cx/dh_auto_test(1)), indeed - and this behaviour can be overridden with by adding `nocheck` to var `DEB_BUILD_OPTIONS=nocheck`. I built it into `debian/rules` instead of `build.sh` - I hope this is ok

@njam please review

**Comment by njam** [comment]
I didn't check the first two commits (two long). Did you have any custom adjustments there besides the import from ubuntu?

Rest lgtm

**Comment by ppp0** [comment]
Sorry I should have told you that the only change (besides requiring `apt::source::cargomedia` and the newest libx265-dev) is https://github.com/ppp0/debian-packages/commit/e1328d302607a875ecc2ae01406242b39fa41a73

**Comment by njam** [comment]
ok thanks, lgtm

**Pull request merged**
