### PR TITLE
Upgrade janus-gateway-rtpbroadcast to v0.0.28

### PR DESCRIPTION
**Pull request by kris-lab**
https://github.com/cargomedia/janus-gateway-rtpbroadcast/releases/tag/v0.0.28

### CODE REVIEW

**Comment by kris-lab** [comment]
@njam have a look please

**Comment by njam** [comment]
lgtm

btw once we migrate the last janus machine to Jessie we can drop all other codenames here imo.

**Comment by kris-lab** [comment]
ok, sgtm

**Comment by kris-lab** [comment]
synced

**Pull request merged**
