### PR TITLE
Fix janus versioning, take2

### PR DESCRIPTION
**Pull request by ppp0**
follow-up of #102

### CODE REVIEW

**Comment by ppp0** [comment]
As discovered
```bash
sudo dpkg --compare-versions 0.0.9.adf88c-jessie2 lt 0.0.9~git160318.088882-jessie3 ;echo $?
1
```

but

```bash
sudo dpkg --compare-versions 0.0.9.adf88c-jessie2 lt 0.0.9.git160318.088882-jessie3 ;echo $?
0
```


@njam please review

**Comment by njam** [comment]
How about `<upstream-version>.git<internal-counter>.<commit>-<internal-version>`?
E.g.:
- 0.0.9.git1.abcdef-jessie1
- 0.0.9.git2.abcdef-jessie1

**Comment by ppp0** [comment]
@njam please review

**Comment by njam** [comment]
lgtm

**Pull request merged**
