### PR TITLE
Remove ffmpeg debs from live repo

### PR DESCRIPTION
**Pull request by ppp0**

### CODE REVIEW

**Comment by ppp0** [comment]
@njam please review

**Comment by njam** [comment]
lgtm

**Comment by ppp0** [comment]
Manual removing from repo db:

```sh
eval $(gpg-agent --daemon)
for repo in wheezy vivid; do
for i in ffmpeg-dbg ffmpeg-doc ffmpeg libav-tools libavcodec-dev libavcodec-extra libavcodec-ffmpeg-extra56 libavcodec-ffmpeg56 libavdevice-dev libavdevice-ffmpeg56 libavfilter-dev libavfilter-ffmpeg5 libavformat-dev libavformat-ffmpeg56 libavresample-dev libavresample-ffmpeg2 libavutil-dev libavutil-ffmpeg54 libpostproc-dev libpostproc-ffmpeg53 libswresample-dev libswresample-ffmpeg1 libswscale-dev libswscale-ffmpeg3; do reprepro -b repo/ remove ${repo} ${i};done;done
```

**Comment by njam** [comment]
Couldn't you just `rm -rf repo`, then recreate and sync?

**Comment by ppp0** [comment]
ok, next time :)

**Pull request merged**
