### PR TITLE
Add gstreamer-plugins-base and newest liborc dependency

### LINKED ISSUE #9: Add gstreamer-plugins-base
Backport from http://packages.ubuntu.com/xenial/gstreamer0.10-plugins-base or even use http://packages.ubuntu.com/vivid/gstreamer0.10-plugins-base - they have the same dependencies and version numbers... Check if it works, though

### PR DESCRIPTION
**Pull request by dergraf**
added gst-plugins-base which required a more recent version of orc that's included in this PR too.

### CODE REVIEW

**Comment by dergraf** [comment]
NOTE: the repo isn't updated with the new packages

**Comment by ppp0** [comment]
@njam we are thinking about splitting the key signing into a separate `sign.sh` - I'm not sure since it's being handled by `reprepo` which does a bit more than just signing.. Ideas? The rationale is to allow external contributors to code and keep the keys separate?

**Comment by ppp0** [comment]
lgtm

as discussed, may be add sharness tests to both `gst-plugins-base` and `liborc` ?

**Comment by ppp0** [comment]
test being added in #20

**Pull request merged**
