### PR TITLE
streamline init scripts

### PR DESCRIPTION
**Pull request by ppp0**

### CODE REVIEW

**Comment by ppp0** [comment]
@njam please review

**Comment by njam** [comment]
- Move "oknodo" before "retry" (convention)
- mysql-proxy/debian/init: Also add "oknodo"?
- mysql-proxy/debian/init: Remove "quiet"?

**Comment by ppp0** [comment]
- Makes sense
- mysqlproxy's restart streamlined

@njam please re-review

**Comment by njam** [comment]
lgtm

**Comment by njam** [comment]
you're gonna bump versions here?

**Comment by ppp0** [comment]
@njam please have a look

**Comment by njam** [comment]
Main version should reflect upstream version.
Append package version (what format?)

**Comment by ppp0** [comment]
@njam hope it's good now

**Comment by njam** [comment]
lgtm

**Comment by ppp0** [comment]
generating packages and syncing to S3

**Pull request merged**
