### PR TITLE
Update janus and plugins

### PR DESCRIPTION
**Pull request by ppp0**

### CODE REVIEW

**Comment by ppp0** [comment]
@kris-lab this compiles without problems. Please review. 

Old and new cfg file diffs: none

**Comment by kris-lab** [comment]
looks good. let's wait for plugins, update them with new janus and release all together!

**Comment by tomaszdurka** [comment]
@ppp0 please also update init script to consider pidfile when checking status of the service.

Replace
```
status_of_proc "$DAEMON_NAME" "$DAEMON" && exit 0 || exit $?
```
with
```
status_of_proc -p "$PIDFILE" "$DAEMON_NAME" "$DAEMON" && exit 0 || exit $?
```

**Comment by njam** [comment]
@ppp0 @kris-lab let's create a DEB with current versions

Waiting for https://github.com/cargomedia/janus-gateway-rtpbroadcast/issues/77

**Comment by kris-lab** [comment]
@ppp0 can we stick to this version `08888212c99f715061bcc833f47dd36aabb382ed`?

See also:
- https://github.com/cargomedia/janus-gateway-rtpbroadcast/pull/77
- https://github.com/cargomedia/janus-gateway-audioroom/pull/36

**Comment by ppp0** [comment]
@kris-lab please review

**Comment by ppp0** [comment]
Updated init script according to https://github.com/cargomedia/debian-packages/pull/101#issuecomment-194231607

**Comment by ppp0** [comment]
@kris-lab please review

**Comment by kris-lab** [comment]
- jessy/audioroom `setup.sh` is not commited?

**Comment by kris-lab** [comment]
lgtm! as discussed let's merge and deploy tomorrow.

**Comment by ppp0** [comment]
@kris-lab thanks! May be double-check again?

Merging (and syncing with repo) will happen tomorrow during maintenance window for bulldogs

**Pull request merged**
