### PR TITLE
Upgrade janus-gateway-rtpbroadcast to 0.0.5

### PR DESCRIPTION
**Pull request by kris-lab**
https://github.com/cargomedia/janus-gateway-rtpbroadcast/releases/tag/v0.0.5

### CODE REVIEW

**Comment by kris-lab** [comment]
@njam please have a look

**Comment by njam** [comment]
The ubuntu version should end in `-vivid1` and not `-ubuntu1` - could you adjust it here?

Also just to be sure: did you build each package on the corresponding VM?

**Comment by kris-lab** [comment]
> The ubuntu version should end in -vivid1 and not -ubuntu1 - could you adjust it here?

ok, done for last release. the rest I have left like before?

> Also just to be sure: did you build each package on the corresponding VM?

yes, done on dedicated VMs.

**Comment by njam** [comment]
lgtm!

**Comment by kris-lab** [comment]
synced!

**Pull request merged**
