### PR TITLE
[Jessie] Add mysql-proxy

### PR DESCRIPTION
**Pull request by ppp0**
For jessie it's officially still v0.8.1, we run v0.8.4

### CODE REVIEW

**Comment by ppp0** [comment]
Update to v0.8.5 for both jessie and wheezy

**Comment by ppp0** [comment]
@kris-lab please review

**Comment by kris-lab** [comment]
What happens with this files:
- `packages/wheezy/usrsctp/debian/postrm → packages/jessie/mysql-proxy/debian/postrm`
- `packages/{wheezy/usrsctp → jessie/mysql-proxy}/debian/tests/sharness.sh`

**Comment by ppp0** [comment]
interesting... These are files which I originally copied (not moved) and which I later did not have to modify

Please compare with
- https://github.com/cargomedia/debian-packages/blob/master/packages/wheezy/mysql-proxy/debian/postrm
- https://github.com/cargomedia/debian-packages/blob/master/packages/wheezy/mysql-proxy/debian/postinst
etc

@kris-lab please re-review

**Comment by kris-lab** [comment]
ok then! lgtm

**Pull request merged**
