### PR TITLE
Add ffmpeg-cm package

### PR DESCRIPTION
**Pull request by ppp0**
Related: https://github.com/cargomedia/debian-packages/pull/82 https://github.com/cargomedia/debian-packages/pull/90 https://github.com/cargomedia/debian-packages/pull/89 https://github.com/cargomedia/debian-packages/pull/91

=== UPDATED by @ppp0
These are the codecs for which `ffmpeg` is built. `DE` meaning Decoder and Encoder (the crucial part being the encoder)

```
$ ffmpeg -codecs |grep DE
ffmpeg version 2.8.6 Copyright (c) 2000-2016 the FFmpeg developers
  built with gcc 4.9.2 (Debian 4.9.2-10)
  configuration: --prefix=/usr --enable-gpl --enable-shared --enable-version3 --enable-runtime-cpudetect --enable-libvpx --enable-libopus
  libavutil      54. 31.100 / 54. 31.100
  libavcodec     56. 60.100 / 56. 60.100
  libavformat    56. 40.101 / 56. 40.101
  libavdevice    56.  4.100 / 56.  4.100
  libavfilter     5. 40.101 /  5. 40.101
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  2.101 /  1.  2.101
  libpostproc    53.  3.100 / 53.  3.100
 DEVI.S alias_pix            Alias/Wavefront PIX image
 DEVIL. amv                  AMV Video
 DEV..S apng                 APNG (Animated Portable Network Graphics) image
 DEVIL. asv1                 ASUS V1
 DEVIL. asv2                 ASUS V2
 DEVI.. avrp                 Avid 1:1 10-bit RGB Packer
 DEVI.. avui                 Avid Meridien Uncompressed
 DEVI.. ayuv                 Uncompressed packed MS 4:4:4:4
 DEVI.S bmp                  BMP (Windows and OS/2 bitmap)
 DEV.L. cinepak              Cinepak
 DEVIL. cljr                 Cirrus Logic AccuPak
 DEVIL. dnxhd                VC3/DNxHD
 DEVI.S dpx                  DPX (Digital Picture Exchange) image
 DEVIL. dvvideo              DV (Digital Video)
 DEV..S ffv1                 FFmpeg video codec #1
 DEVI.S ffvhuff              Huffyuv FFmpeg variant
 DEV..S flashsv              Flash Screen Video v1
 DEV.L. flashsv2             Flash Screen Video v2
 DEV.L. flv1                 FLV / Sorenson Spark / Sorenson H.263 (Flash Video) (decoders: flv ) (encoders: flv )
 DEV..S gif                  GIF (Graphics Interchange Format)
 DEV.L. h261                 H.261
 DEV.L. h263                 H.263 / H.263-1996, H.263+ / H.263-1998 / H.263 version 2
 DEV.L. h263p                H.263+ / H.263-1998 / H.263 version 2
 DEVI.S huffyuv              HuffYUV
 DEVILS jpeg2000             JPEG 2000
 DEVILS jpegls               JPEG-LS
 D.VIL. mdec                 Sony PlayStation MDEC (Motion DECoder)
 DEVIL. mjpeg                Motion JPEG
 DEV.L. mpeg1video           MPEG-1 video (decoders: mpeg1video mpeg1video_vdpau )
 DEV.L. mpeg2video           MPEG-2 video (decoders: mpeg2video mpegvideo mpegvideo_vdpau )
 DEV.L. mpeg4                MPEG-4 part 2 (decoders: mpeg4 mpeg4_vdpau )
 DEV.L. msmpeg4v2            MPEG-4 part 2 Microsoft variant version 2
 DEV.L. msmpeg4v3            MPEG-4 part 2 Microsoft variant version 3 (decoders: msmpeg4 ) (encoders: msmpeg4 )
 DEV.L. msvideo1             Microsoft Video 1
 DEVI.S pam                  PAM (Portable AnyMap) image
 DEVI.S pbm                  PBM (Portable BitMap) image
 DEVI.S pcx                  PC Paintbrush PCX image
 DEVI.S pgm                  PGM (Portable GrayMap) image
 DEVI.S pgmyuv               PGMYUV (Portable GrayMap YUV) image
 DEV..S png                  PNG (Portable Network Graphics) image
 DEVI.S ppm                  PPM (Portable PixelMap) image
 DEVIL. prores               Apple ProRes (iCodec Pro) (decoders: prores prores_lgpl ) (encoders: prores prores_aw prores_ks )
 DEV..S qtrle                QuickTime Animation (RLE) video
 DEVI.S r10k                 AJA Kona 10-bit RGB Codec
 DEVI.S r210                 Uncompressed RGB 10-bit
 DEVI.S rawvideo             raw video
 DEV.L. roq                  id RoQ video (decoders: roqvideo ) (encoders: roqvideo )
 DEV.L. rv10                 RealVideo 1.0
 DEV.L. rv20                 RealVideo 2.0
 DEVI.S sgi                  SGI image
 DEV.LS snow                 Snow
 DEVI.S sunrast              Sun Rasterfile image
 DEV.L. svq1                 Sorenson Vector Quantizer 1 / Sorenson Video 1 / SVQ1
 DEVI.S targa                Truevision Targa image
 DEVI.S tiff                 TIFF image
 DEVI.S utvideo              Ut Video
 DEVI.S v210                 Uncompressed 4:2:2 10-bit
 DEVI.. v308                 Uncompressed packed 4:4:4
 DEVI.. v408                 Uncompressed packed QT 4:4:4:4
 DEVI.S v410                 Uncompressed 4:4:4 10-bit
 DEV.L. vp8                  On2 VP8 (decoders: vp8 libvpx ) (encoders: libvpx )
 DEV.L. vp9                  Google VP9 (decoders: vp9 libvpx-vp9 ) (encoders: libvpx-vp9 )
 DEV.L. wmv1                 Windows Media Video 7
 DEV.L. wmv2                 Windows Media Video 8
 DEVI.S xbm                  XBM (X BitMap) image
 DEVIL. xface                X-face image
 DEVI.S xwd                  XWD (X Window Dump) image
 DEVI.. y41p                 Uncompressed YUV 4:1:1 12-bit
 DEVI.. yuv4                 Uncompressed packed 4:2:0
 DEVI.S zlib                 LCL (LossLess Codec Library) ZLIB
 DEV..S zmbv                 Zip Motion Blocks Video
 DEA.L. aac                  AAC (Advanced Audio Coding) (decoders: aac aac_fixed )
 DEA.L. ac3                  ATSC A/52A (AC-3) (decoders: ac3 ac3_fixed ) (encoders: ac3 ac3_fixed )
 DEA.L. adpcm_adx            SEGA CRI ADX ADPCM
 DEA.L. adpcm_g722           G.722 ADPCM (decoders: g722 ) (encoders: g722 )
 DEA.L. adpcm_g726           G.726 ADPCM (decoders: g726 ) (encoders: g726 )
 DEA.L. adpcm_ima_qt         ADPCM IMA QuickTime
 DEA.L. adpcm_ima_wav        ADPCM IMA WAV
 DEA.L. adpcm_ms             ADPCM Microsoft
 DEA.L. adpcm_swf            ADPCM Shockwave Flash
 DEA.L. adpcm_yamaha         ADPCM Yamaha
 DEA..S alac                 ALAC (Apple Lossless Audio Codec)
 DEA.L. comfortnoise         RFC 3389 Comfort Noise
 DEA.LS dts                  DCA (DTS Coherent Acoustics) (decoders: dca ) (encoders: dca )
 DEA.L. eac3                 ATSC A/52B (AC-3, E-AC-3)
 DEA..S flac                 FLAC (Free Lossless Audio Codec)
 DEA.L. g723_1               G.723.1
 DEA.L. mp2                  MP2 (MPEG audio layer 2) (decoders: mp2 mp2float ) (encoders: mp2 mp2fixed )
 DEA.L. nellymoser           Nellymoser Asao
 DEA.L. opus                 Opus (Opus Interactive Audio Codec) (decoders: opus libopus ) (encoders: libopus )
 DEA.L. pcm_alaw             PCM A-law / G.711 A-law
 DEA..S pcm_f32be            PCM 32-bit floating point big-endian
 DEA..S pcm_f32le            PCM 32-bit floating point little-endian
 DEA..S pcm_f64be            PCM 64-bit floating point big-endian
 DEA..S pcm_f64le            PCM 64-bit floating point little-endian
 DEA.L. pcm_mulaw            PCM mu-law / G.711 mu-law
 DEA..S pcm_s16be            PCM signed 16-bit big-endian
 DEA..S pcm_s16be_planar     PCM signed 16-bit big-endian planar
 DEA..S pcm_s16le            PCM signed 16-bit little-endian
 DEA..S pcm_s16le_planar     PCM signed 16-bit little-endian planar
 DEA..S pcm_s24be            PCM signed 24-bit big-endian
 DEA..S pcm_s24daud          PCM D-Cinema audio signed 24-bit
 DEA..S pcm_s24le            PCM signed 24-bit little-endian
 DEA..S pcm_s24le_planar     PCM signed 24-bit little-endian planar
 DEA..S pcm_s32be            PCM signed 32-bit big-endian
 DEA..S pcm_s32le            PCM signed 32-bit little-endian
 DEA..S pcm_s32le_planar     PCM signed 32-bit little-endian planar
 DEA..S pcm_s8               PCM signed 8-bit
 DEA..S pcm_s8_planar        PCM signed 8-bit planar
 DEA..S pcm_u16be            PCM unsigned 16-bit big-endian
 DEA..S pcm_u16le            PCM unsigned 16-bit little-endian
 DEA..S pcm_u24be            PCM unsigned 24-bit big-endian
 DEA..S pcm_u24le            PCM unsigned 24-bit little-endian
 DEA..S pcm_u32be            PCM unsigned 32-bit big-endian
 DEA..S pcm_u32le            PCM unsigned 32-bit little-endian
 DEA..S pcm_u8               PCM unsigned 8-bit
 DEA.L. ra_144               RealAudio 1.0 (14.4K) (decoders: real_144 ) (encoders: real_144 )
 DEA.L. roq_dpcm             DPCM id RoQ
 DEA..S s302m                SMPTE 302M
 DEA... sonic                Sonic
 DEA..S tta                  TTA (True Audio)
 DEA.L. vorbis               Vorbis
 DEA.LS wavpack              WavPack
 DEA.L. wmav1                Windows Media Audio 1
 DEA.L. wmav2                Windows Media Audio 2
 DES... ass                  ASS (Advanced SSA) subtitle
 DES... dvb_subtitle         DVB subtitles (decoders: dvbsub ) (encoders: dvbsub )
 DES... dvd_subtitle         DVD subtitles (decoders: dvdsub ) (encoders: dvdsub )
 DES... mov_text             MOV text
 DES... ssa                  SSA (SubStation Alpha) subtitle
 DES... subrip               SubRip subtitle (decoders: srt subrip ) (encoders: srt subrip )
 DES... webvtt               WebVTT subtitle
 DES... xsub                 XSUB
```

### CODE REVIEW

**Comment by ppp0** [comment]
OK so this is a new try. I reconstructed the build process in https://github.com/cargomedia/puppet-packages/blob/master/modules/ffmpeg/templates/install.sh **except** for dependencies out of `deb-multimedia` repo (libfaac AAC Audio Encoder and `mjpgtools`)

Included are these codecs:
- opus
- vpx

@kris-lab I hope this is the requirement

The rationale for renaming the package is that `ffmpeg` comes with a lot of additional packages. Such as the `libav*` [required here](https://github.com/cargomedia/puppet-packages/blob/master/modules/janus/manifests/source.pp#L29)

**Comment by ppp0** [comment]
```
 WARNING: library configuration mismatch
  avutil      configuration: --prefix=/usr --enable-gpl --enable-shared --enable-version3 --enable-runtime-cpudetect --enable-libvpx --enable-libopus
  avcodec     configuration: --prefix=/usr --enable-gpl --enable-shared --enable-version3 --enable-runtime-cpudetect --enable-libvpx --enable-libopus
  avformat    configuration: --prefix=/usr --enable-gpl --enable-shared --enable-version3 --enable-runtime-cpudetect --enable-libvpx --enable-libopus
  avdevice    configuration: --prefix=/usr --enable-gpl --enable-shared --enable-version3 --enable-runtime-cpudetect --enable-libvpx --enable-libopus
  avfilter    configuration: --prefix=/usr --enable-gpl --enable-shared --enable-version3 --enable-runtime-cpudetect --enable-libvpx --enable-libopus
  swscale     configuration: --prefix=/usr --enable-gpl --enable-shared --enable-version3 --enable-runtime-cpudetect --enable-libvpx --enable-libopus
  swresample  configuration: --prefix=/usr --enable-gpl --enable-shared --enable-version3 --enable-runtime-cpudetect --enable-libvpx --enable-libopus
  postproc    configuration: --prefix=/usr --enable-gpl --enable-shared --enable-version3 --enable-runtime-cpudetect --enable-libvpx --enable-libopus
  libavutil      54. 31.100 / 54. 31.100
  libavcodec     56. 60.100 / 56. 60.100
  libavformat    56. 40.101 / 56. 40.101
  libavdevice    56.  4.100 / 56.  4.100
  libavfilter     5. 40.101 /  5. 40.101
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  2.101 /  1.  2.101
```

hmmm

**Comment by ppp0** [comment]
OK - I was able to load the libraries in the correct location and to issue a `ldconfig` as postinst in order to have all in the proper place

@njam please review

**Comment by njam** [comment]
I wanted to briefly test the DEB, but the contained "data.tar.gz" is empty - the package doesn't install any files.

Can you look into this? Once the DEB is ready let's test it in an SK VM, making sure it can do those operations we need.

**Comment by ppp0** [comment]
Very sorry about that. I completely re-did `debian/rules` and patched ffpmeg's `configure` a bit in order to be able to use `dh_configure` without fuss

Now it really should be working @njam would you please check / review? Thanks

**Comment by njam** [comment]
I installed this into an SK VM and can confirm that it can process our workloads fine!
lgtm.

I've opened a puppet-packages ticket here with additional notes: https://github.com/cargomedia/puppet-packages/issues/1208

**Pull request merged**
