### PR TITLE
Upgrade janus-gateway-rtpbroadcast

### PR DESCRIPTION
**Pull request by kris-lab**
https://github.com/cargomedia/janus-gateway-rtpbroadcast/releases/tag/v0.0.10

### CODE REVIEW

**Comment by kris-lab** [comment]
@njam please review

**Comment by njam** [comment]
- Version in setup.sh is not in sync with changelog?
- We also need to do audio plugin, should we do it in 1 go? Up to you.

**Comment by kris-lab** [comment]
> Version in setup.sh is not in sync with changelog?

this is fine. releases of plugin are not in sync with DEBs.

> We also need to do audio plugin, should we do it in 1 go? Up to you.

Audio plugin works fine.

**Comment by kris-lab** [comment]
@njam please re-review

**Comment by njam** [comment]
lgtm

**Comment by kris-lab** [comment]
released

**Pull request merged**
