### PR TITLE
Drop support for libx265 in gst-plugins-bad

### PR DESCRIPTION
**Pull request by kris-lab**

### CODE REVIEW

**Comment by kris-lab** [comment]
@njam please review

**Comment by njam** [comment]
How did you downgrade libx265? There's no reference in the code. When we build the package again I guess we need to install 1.5 specifically?

**Comment by kris-lab** [comment]
If you build package with `libx265` in version `1.7.1` then it somehow require this version during DEB installation - even if there is no reference in code.

I have downgraded `libx265` to `1.5` (which is available in Ubuntu/vivid) and I have rebuilt/re-compiled the code. It does not complain about wrong version anymore (still there is no reference in debs/control).

**Comment by njam** [comment]
Ok, vivid's libx265 is 1.5.1: http://packages.ubuntu.com/vivid/libx265-dev

so all good!

**Comment by kris-lab** [comment]
synced

**Comment by ppp0** [comment]
You forgot the README (https://github.com/cargomedia/debian-packages/pull/116)

`vagrant@debian-8-amd64-default:/vagrant$ python doc.py` does the trick.. we should think of doing this automatically somehow (as part of build.sh ?)

**Comment by kris-lab** [comment]
automation here would be nice. Usually it is not a problem, but if you upgrade tons of packages then it might happen.

**Pull request merged**
