### PR TITLE
[Jessie] Add RAID packages

### PR DESCRIPTION
**Pull request by ppp0**
- [x] arcconf - done in https://github.com/cargomedia/debian-packages/issues/97
- [x] hpacucli
- [x] hpssacli
- [x] sas2ircu
- [x] storcli

### CODE REVIEW

**Comment by ppp0** [comment]
@njam please review

**Comment by njam** [comment]
- changelog: I think all changelogs should have only 1 entry - initial import?
- hpssacli setup.sh: Why change the download URL? If there's a reason to change it, then we should probably change it for all codenames?

**Comment by ppp0** [comment]
* well, depends what you want to track. I copied it from vivid, so that's accurate, but I can change it
* I had to change it because the old URL is stale - I can adapt the other versions

**Comment by njam** [comment]
- changelog: it just looked weird, because the version differs only in the codename - not sure if "dpkg" could for example tell which version is earlier and which later. Let's stick to 1 version therefore?
- Yes, please change it everywhere

**Comment by ppp0** [comment]
@njam please review

**Comment by njam** [comment]
lgtm

**Pull request merged**
