### PR TITLE
Upgrade janus-gateway-audioroom and janus-gateway-rtpbroadcast

### PR DESCRIPTION
**Pull request by kris-lab**
- https://github.com/cargomedia/janus-gateway-rtpbroadcast/releases/tag/v0.0.8
- https://github.com/cargomedia/janus-gateway-audioroom/releases/tag/v0.0.7

### CODE REVIEW

**Comment by kris-lab** [comment]
@njam please review

**Comment by njam** [comment]
lgtm

Maybe change the audioroom version also from `-ubuntu1` to `-vivid1`?

**Comment by kris-lab** [comment]
@njam please re-review

**Comment by njam** [comment]
lgtm

**Comment by kris-lab** [comment]
released

**Pull request merged**
