### PR TITLE
Drop Wheezy packages

### PR DESCRIPTION
**Pull request by ppp0**
@cargomedia/devops  opinion?

### CODE REVIEW

**Comment by ppp0** [comment]
@kris-lab please review

**Comment by ppp0** [comment]
@njam please review

**Comment by njam** [comment]
- README: remove wheezy
- repo: remove wheezy and sync?

**Comment by ppp0** [comment]
* Isn't it removed?
* Will do after merging

**Comment by njam** [comment]
ah actually it's `README.md.in`.

**Pull request merged**
