### PR TITLE
Backport x265 package

### PR DESCRIPTION
**Pull request by ppp0**

### CODE REVIEW

**Comment by ppp0** [comment]
@njam please review

**Comment by njam** [comment]
We've been using x264 so far, isn't it something different?
https://en.wikipedia.org/wiki/X265

Also, do we need any of this, as we're using WebM/VP8 only atm @kris-lab ?

**Comment by ppp0** [comment]
Agree we're not needing this, but I'm trying to package https://github.com/cargomedia/debian-packages/issues/82 as closely as possible to http://packages.ubuntu.com/xenial/ffmpeg

Shall I not?

**Comment by njam** [comment]
Ok let's keep it as it's already done!
- setup.sh: Should we download from the original source (http://ftp.videolan.org/pub/videolan/x265/) ?

**Pull request merged**
